### ISSUE TITLE
Setup project

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr#1]
- Initialize new Spring Boot project using JDK 17 and Spring 5.3
- Build project using Gradle 7.5

Just need the skeleton of the project for now

**Comment by joshgarde** [comment]
PR open - https://github.com/podaac/swodlr/pull/2

I would be happy to throw in some standard boiler plate GitHub templates from PODAAC like the PR template. I could probably also start setting up GH Actions just so it's there for later.
