### ISSUE TITLE
As an end user, I want to be able to select a configuration provided by the API

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#12]
Implement pre-defined configurations for users to select:

(1) output_granule_extent_flag  (e.g., 0)
(2) raster_resolution                    (e.g., 100, 200)
(3) output_sampling_grid_type (e.g., utm)
(4) utm_zone_adjust                   (e.g., 0)
(5) mgrs_band_adjust                 (e.g., 0)

User provides Cycle/Pass/Scene IDs & select from above pre-defined configurations provided by our API.

**Comment by joshgarde** [comment]
Closed with merge #28
