### ISSUE TITLE
Update readme.md to be more descriptive for swodlr repos

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#128]
1. [swodlr-api](https://github.com/podaac/swodlr-api)
2. [swodlr-async-update](https://github.com/podaac/swodlr-async-update)
3. [wodlr-ingest-to-sds](https://github.com/podaac/swodlr-ingest-to-sds)
4. [swodlr-raster-create](https://github.com/podaac/swodlr-raster-create)
5. [swodlr-user-notify](https://github.com/podaac/swodlr-user-notify)

Provide a description of 
- how components interact with each other
- the workflow of each component

**Comment by joshgarde** [comment]
All PRs open and ready for review
