### ISSUE TITLE
As a developer, I want to be able to query existing metadata in CMR so that I can get a preliminary set of L2_HR_PIXC and PIXCVec products

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#16]
Implement API to query existing metadata in CMR to get a preliminary set of L2 PIXC & PIXCVec products

**Comment by joshgarde** [comment]
Current estimated ticket work:
- [X] OAuth auth token injection into CMR requests
- [ ] CMR Pagination
- [ ] GranuleMetadata class
- [ ] Integration with controllers/services

**Comment by joshgarde** [comment]
PR opened - #38

**Comment by joshgarde** [comment]
PR merged
