### ISSUE TITLE
As a developer, I want to be able to query augmented L2_HR_PIXC and PIXCVec metadata (cycle, pass, scene ID) in CMR UAT POCUMULUS so that I can get list of L2 products

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#17]

**Comment by joshgarde** [comment]
PR opened on `cmr-graphql` per @frankinspace's suggestion

https://github.com/nasa/cmr-graphql/pull/36

**Comment by joshgarde** [comment]
PR merged; blocked until 1/25 when CMR pushes changes to UAT

**Comment by joshgarde** [comment]
Swodlr PR ready for CMR UAT deployment; https://github.com/podaac/swodlr/pull/42

**Comment by joshgarde** [comment]
Closed with merge of #42
