### ISSUE TITLE
Setup RDS database

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr#3]
This service is going to have to connect to an RDS instance to store state. Need to setup an RDS instance using terraform.

AC:
- Terraform scripts written and can be manually applied to SIT environment
- RDS instance is created with 2 users: an administrator with ownership permissions and an application user with permissions limited to a specific schema to be used for the application.

**Comment by joshgarde** [comment]
PR opened - https://github.com/podaac/swodlr/pull/4

**Comment by joshgarde** [comment]
PR merged - https://github.com/podaac/swodlr/pull/4
