### ISSUE TITLE
As an automate regression test, I want to test that I can log in with EDL and query the API so that I can confirm EDL login is working

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr#44]
AC:

- Automated test runs successfully that logs in a test user with EDL

**Comment by Phoeneix** [comment]
Zoltan here,
I have a few questions:
- Which API endpoints needs to be checked?
- Do you want me to develop the test code/ framework here, or can use the existing one?
- Where do you want the tests to be added and executed? Jenkins or Github action? (The later only possible of the code is in the same repository)

**Comment by viviant100** [comment]
- API endpoint: https://d15gds5czd9p7k.cloudfront.net/
- test code/frame work goes here: https://github.com/podaac/swodlr-functional-tests
- Github action

**Comment by frankinspace** [comment]
Waiting on deployment to UAT in order to run tests from a public client.

**Comment by viviant100** [comment]
requirement documentation of (@joshgarde)

1. API endpoints
2. Expected inputs/outputs
3. test case

**Comment by viviant100** [comment]
@Phoeneix please see  https://github.com/podaac/swodlr/wiki/Getting-Started-with-SWODLR%E2%80%90API

**Comment by viviant100** [comment]
Pending auth refactor being merged.

**Comment by viviant100** [comment]
Per [PODAAC-5480 ](https://jira.jpl.nasa.gov/browse/PODAAC-5480)test implementation:

- PR opened on 11/28/23: https://github.com/podaac/swodlr-functional-tests/pull/3

**Comment by viviant100** [comment]
test passed in UAT: https://github.com/podaac/swodlr-functional-tests/actions/runs/7479400696
![Screenshot 2024-01-10 at 11 02 07 AM](https://github.com/podaac/swodlr/assets/22924433/5abd3538-bbd6-4834-bbac-7518467df5d9)
