### ISSUE TITLE
Develop SNS Messaging layer

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#48]
![Screenshot 2023-04-06 at 10 39 08 AM](https://user-images.githubusercontent.com/22924433/232324478-ce85f15e-02e2-4e17-b4ff-7f6ba380322c.png)

https://github.com/podaac/swodlr-async-update

**Comment by joshgarde** [comment]
PR merged - https://github.com/podaac/swodlr-async-update/pull/1
