### ISSUE TITLE
Implement basic API

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr#5]
After some initial discussions about the proposed architecture (https://github.com/podaac/swodlr/wiki/Architecture), implement a simple API for working with the domain objects discussed.

Acceptance Criteria:

- User should be able to create an L2 Raster Product object
- User can view a L2 Raster Product object that was previously created

**Comment by joshgarde** [comment]
PR opened - https://github.com/podaac/swodlr/pull/6

**Comment by joshgarde** [comment]
Closed w/ #6
