### ISSUE TITLE
user-notify: Initial implementation

### ISSUE THREAD

**Issue by joshgarde** [podaac/swodlr#59]
Initial implementation, linting, testing, and CI/CD

**Comment by frankinspace** [comment]
Note: the provided SES service runs only in `us-east-1`. So when using boto3 to send messages with the SES API, need to make sure to set the region to `us-east-1` in the boto3 client.

**Comment by joshgarde** [comment]
https://github.com/podaac/swodlr-user-notify/pull/1
Merged
