### ISSUE TITLE
Backend and microservices improvements

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#68]
- [x] 23.3.1 (sprint 1): cleanup/error handling 
    - [x]      #61 
    - [x]      #62 
- [x] 23.3.2 (sprint 2): #63 
- [ ] 23.3.3 (sprint 3): #64 
- [ ] 23.3.4 (sprint 4): 
    - [ ]       #65 
    - [ ]       #66

**Comment by frankinspace** [comment]
Remaining tasks are being tracked in future milestones.
