### ISSUE TITLE
Implement tests for API

### ISSUE THREAD

**Issue by frankinspace** [podaac/swodlr#7]
Create tests for the API using an in memory database as storage.

A few test cases that should be present:
- Given product does not exist, create new raster product. Validate new product exists
- Given product exists, lookup raster product. Validate product returned
- Given product exists, lookup status of raster product. Validate correct status returned
- Given product does not exist, lookup raster product. Validate error returned indicating product not found

**Comment by joshgarde** [comment]
Closed with PR merge of #8
