### ISSUE TITLE
Update s3 Bucket Path 

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#81]
(1)  s3://<bucket_name>/uuid/granules
-  does "uuid" trace back to RDS schema currently?  
    - Yes, the full path is  s3://<bucket_name>/{product_id}/{partial_hash}/{original_filename} 

(2) Update RDS schema documentation on wiki

**Comment by joshgarde** [comment]
The pattern discussed for the updated S3 paths is as follows:

`/{product_id}/{partial_hash}/{original_filename}`

This should ensure that our S3 naming is unique in the vast majority of cases where the SDS provides a filename which is the same as an existing output in the bucket

**Comment by joshgarde** [comment]
PR opened: https://github.com/podaac/swodlr-raster-create/pull/14

**Comment by joshgarde** [comment]
PR merged
