### ISSUE TITLE
SWODLR metric tools

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#84]
Collaborate with the I&A team to enable bucket logging on the SWODLR S3 bucket. This will allow us to gather metrics related to:
- Downloaded granules
- Granule download frequency

**Comment by viviant100** [comment]
using programmatic approach via credential to access cloud metric

**Comment by frankinspace** [comment]
This ticket complete as we have determined approach and opened follow on ticket #64

**Comment by viviant100** [comment]
related metric ticket is in Ingest data from CloudWatch Log Groups over to Earthdata Cloud's Metrics [#94](https://github.com/podaac/swodlr/issues/94)
