### ISSUE TITLE
Address 11 low findings in Qualys scan (SWOLDR UAT)

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#87]
11 low findings were found in the Web Application Vulnerability Scan.  Once it's fixed, security team will rescan uat website.

**Comment by joshgarde** [comment]
https://github.com/podaac/swodlr-api/pull/18

**Comment by viviant100** [comment]
backend : turn off active development profile. frontend: create 404 page

**Comment by viviant100** [comment]
will be addressed after auth refactor PR is merged
