### ISSUE TITLE
CICD for API (UAT)

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#88]
Apply build pipeline to the `swodlr-api` repo:
-   Add deployment steps to the existing `swodlr-api` github action workflow

**Comment by jonathansmolenski** [comment]
I'm up to the actual terraform deployment step now, with the environment and credentials all configured correctly.  I needed to add the SERVICE_UAT credentials to github so this would work properly.  

I'll need to know the actual terraform commands used for this.  I've reached out to @joshgarde for this information, but I figured it's best to document here as well.  

The release logic for this is very very simple, with only an alpha release step.  This might need expanding in the future.
