### ISSUE TITLE
Update Load Balancer to HTTPS listener for DiT 

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#97]
[https://wiki.earthdata.nasa.gov/pages/viewpage.action?spaceKey=ENS&title=PI+24.1+Tenant+Action+Items](https://urldefense.us/v3/__https://wiki.earthdata.nasa.gov/pages/viewpage.action?spaceKey=ENS&title=PI*24.1*Tenant*Action*Items__;KysrKw!!PvBDto6Hs4WbVuu7!KqBu5qkGYv82ryQ9lRVy_ZsEmvSGrN9o0aZlW_t2NfxfDXFMYuM9oOsdoDeT8KtuyMMHkHP9NFx1z7owxJzD4aGZyt7Wkz4$)

**Comment by frankinspace** [comment]
We will need to update the SWODLR load balancer to use HTTPS with a certificate issues by PrivateCA. There are details and a Terraform example shown here: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=335709250#tab-Terraform
